spring:
  application:
    name: anime-service
  profiles:
    active: mysql


  threads:
    virtual:
      enabled: true

server:
  servlet:
    context-path: /
  error:
    include-stacktrace: ON_PARAM
  tomcat:
    threads:
      max: 20
